const ManagementFee = () => (
  <div id="section-management-fee">
    <h2>Management Fee</h2>
    <p>
      Users are charged a 5% management fee. This covers the costs of operating
      El Collectooorr on the Ethereum network with a small buffer in case of
      price spikes. The fee accounts for:
      <ul>
        <li>
          The cost of creating a fractional vault to host the given collection
          (currently, up to 0.4ETH)
        </li>
        <li>The cost of sending collection tokens to the user.</li>
      </ul>
    </p>

    <p>
      Without this fee, someone would need to front the capital required to
      create a fractional vault each time. The fee, therefore, ensures that El
      Collectooorr can run autonomously with minimum human input - it can use
      the capital generated by the fee to create a vault and pay out its
      operators autonomously.
    </p>
  </div>
);

export default ManagementFee;
